name: Test & Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run typecheck
        run: npm run typecheck
      - name: Run lint
        run: npm run lint
      - name: Run tests
        if: false # Enable this when tests are available
        run: npm test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get short SHA
        id: get-short-sha
        run: |
          short_commit_sha=$(echo ${{github.sha}} | cut -c 1-7)
          echo "SHORT_COMMIT_SHA=$short_commit_sha" >> $GITHUB_OUTPUT
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          token_format: 'access_token'
          project_id: ${{ vars.GCP_PROJECT }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build for main branch only
      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.simple
          push: true
          tags: |
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/neon-mcp-server/neon-mcp-server:latest
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/neon-mcp-server/neon-mcp-server:${{ steps.get-short-sha.outputs.SHORT_COMMIT_SHA }}
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/neon-mcp-server/neon-mcp-server:${{ github.ref_name }}

      # Deploy to Cloud Run (main branch only)
      - name: Deploy to Cloud Run
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: neon-mcp-server
          region: ${{ vars.GCP_REGION }}
          image: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/neon-mcp-server/neon-mcp-server:${{ steps.get-short-sha.outputs.SHORT_COMMIT_SHA }}
